### PR TITLE
Tokens to AST

### PR DESCRIPTION
**Pull request by ricardo-emanuel01**
I utilized libcst to modify the approach for parsing the source code of the endpoints. With the generated tree, I designed a DFS like algorithm to retrieve all HTTPExceptions and functions.

I also made some changes on the dependencies to run on my environment.

### CODE REVIEW

**Comment by Kludex** [comment]
We want to create a visitor instead of manually visiting the nodes.

**Comment by ricardo-emanuel01** [comment]
Ok, I'll fix that

**Comment by ricardo-emanuel01** [comment]
I think that the next step is to use libCST matchers to simplify the visitor

**Comment by Kludex** [comment]
I've enabled the pipeline.

We need to fix the tests (or add them...) 👀

**Comment by Kludex** [comment]
Feel free to remove support for python 3.6 and 3.7.

**Comment by ricardo-emanuel01** [comment]
I do not know how to solve that conflict. Could you please suggest something to me, @Kludex?

**Pull request closed without merging**
